---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: podinfo-deamonset
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo:6.3.0
        ports:
        - containerPort: 9898
