name: testing

on:
    push:
      branches:
        - main
    
    pull_request:
      branches:
        - main
 
env:
    TF_VAR_bucket_name: "pikachutestingelvin2024"


jobs:
    unit-test:
      permissions:
        id-token: write
        contents: read
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.18.0-rc.1' # The Go version to download (if necessary) and use.
        
        - name: Install Dependencies
          run: go mod download
          working-directory: ./.github/workflows
        
        - name: Build
          run: go build -o test ./...
        

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::539081213062:role/GithubActionsRole
            
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3

        - name: run test
          run: go test -v ./... -timeout 30m || exit 1
          
  #  cypress-run:
  #    runs-on: ubuntu-latest
  #    needs: unit-test
  #    steps:
  #    - name: Checkout
  #      uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
  #    - name: Cypress run
  #      uses: cypress-io/github-action@v6
